hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root   # must run as root to chown files
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
